version: '3.5'

services:
  app:
    image: vbeni/gdrive-proxy
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
    volumes:
      - './credentials.json:/app/credentials.json'
      - './token.json:/app/token.json'
    restart: unless-stopped
